.PHONY: install_deps test lint

.DEFAULT_GOAL := test

install_deps:
	shards install

test: lint
	crystal spec --rand

lint:
	./bin/ameba

# === Sam shortcut
# next lines are autogenerated and any changes will be discarded after regenerating
CRYSTAL_BIN ?= `which crystal`
SAM_PATH ?= "sam.cr"
.PHONY: sam
sam:
	$(CRYSTAL_BIN) $(SAM_PATH) $(filter-out $@,$(MAKECMDGOALS))
%:
	@:
# === Sam shortcut
